export const GAME_LIST_GET_SUCCESS='GAME_LIST_GET_SUCCESS'
export const GAME_LIST_GET_FAIL='GAME_LIST_GET_FAIL'
export const GAME_GET_SUCCESS='GAME_GET_SUCCESS'
export const GAME_GET_FAIL='GAME_GET_FAIL'